### ISSUE TITLE
CONFIG_TYPE=Existing Not Working As Expected

### ISSUE THREAD

**Issue by knine** [saltstack/salt-windows-msi#101]
From the documentation:

> This setting makes no changes to the existing config and just upgrades/downgrades salt. Makes for easy upgrades. Just run the installer with a silent option. If there is no existing config, then the default is used and master and minion id are applied if passed.

Except it does make changes to the existing config.

Running msiexec with the next update (3003.3 in this case) with options: `/qn CONFIG_TYPE=Existing`

Even if the Minion ID is defined in the `minion_id` file in the existing config, the installer will automatically dump the hostname as the Minion ID into the `minion` file which which will (1) override the `minion_id` file and (2) cause issues if the Minion ID is not the hostname (which is my case because Windows).

>     Salt Version:
>               Salt: 3003.2
>      
>     Dependency Versions:
>               cffi: 1.14.5
>           cherrypy: 18.6.0
>           dateutil: 2.8.1
>          docker-py: Not Installed
>              gitdb: 4.0.5
>          gitpython: 3.1.13
>             Jinja2: 2.11.3
>            libgit2: Not Installed
>           M2Crypto: Not Installed
>               Mako: 1.1.4
>            msgpack: 1.0.2
>       msgpack-pure: Not Installed
>       mysql-python: Not Installed
>          pycparser: 2.20
>           pycrypto: Not Installed
>       pycryptodome: 3.9.8
>             pygit2: Not Installed
>             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
>       python-gnupg: 0.4.6
>             PyYAML: 5.4.1
>              PyZMQ: 18.0.1
>              smmap: 3.0.4
>            timelib: 0.2.4
>            Tornado: 4.5.3
>                ZMQ: 4.3.1
>      
>     System Versions:
>               dist:   
>             locale: cp1252
>            machine: AMD64
>            release: 7
>             system: Windows
>            version: 7 6.1.7601 SP1

**Comment by marbx** [comment]
Hi @knine , thanks for your report, fixes are in progress.

**Comment by twangboy** [comment]
I believe this has been addressed in https://github.com/saltstack/salt-windows-msi/pull/111
If Salt does an RC2 release, we can test it there... otherwise, it will be in the 3004 release.

**Comment by knine** [comment]
Thanks a ton for your work on this. Much appreciated.
