### ISSUE TITLE
MSI does not create all required directories in the root_dir

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt-windows-msi#130]
The MSI is not creating all the required directories in the root dir (`C:\ProgramData\Salt Project\Salt`).

Specifically, it's missing the `var/log/salt` directory, causing the salt-minion to display the following in its logs.

```
[WARNING ] Failed to open log file, do you have permission to write to C:\ProgramData\Salt Project\Salt\var\log\salt\minion?
```

**Comment by marbx** [comment]
How strange.
Not a big deal

**Comment by marbx** [comment]
Not solved by https://github.com/saltstack/salt-windows-msi/pull/131?
