### ISSUE TITLE
Dropping MFC dlls

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-windows-msi#16]
Just a heads-up:

You should be able to drop the MFC dlls if you change:
1. win32gui.SendMessageTimeout -> win32api.SendMessageTimeout
2. pypiwin32 dependency to win32core and win32compat dependency

I have no idea if this will actually work but it does have a reasonable chance if someone wants to try it. I am a maintainer for pypiwin32 so I could change this myself, but I'm not going to push this out for fear of breaking functionality before I get a lot of verification that this works.

**Comment by twangboy** [comment]
@xoviat I submitted a PR for the first item in your list. I'm not sure what you mean by the second.

**Comment by xoviat** [comment]
> I'm not sure what you mean by the second.

Rather than doing this:

```
pip install pypiwin32
```

do this:

```
pip install win32core win32compat
```

It won't work if you leave that part out for sure.

**Comment by twangboy** [comment]
@xoviat Looks like those are Py3 only options. We have to support Py2 for a while longer. We'll have to revisit this once we fully transition to Py3.

**Comment by markuskramerIgitt** [comment]
Good that MFC is gone!

**Comment by markuskramerIgitt** [comment]
`pip install win32core` would be great but https://pypi.org/project/win32core/ says its homepage is  https://sourceforge.net/projects/pywin32 and there it says the project hat moved to https://github.com/mhammond/pywin32

pywin32 has no sub-packages, only the full package (with the MFC). 

https://github.com/mhammond/pywin32/pull/1530 aims at  a subpackage.
