### ISSUE TITLE
Update NSSM to support Win10 Creators update

### ISSUE THREAD

**Issue by yannj-fr** [saltstack/salt-windows-msi#18]
The NSSM 2.24 version is not working with the last "windows 10 creators" update version.
A prebuild version is available, and I have been testing by manually replacing the binary in the salt directory, the result is a success.

The prebuild is available here : http://nssm.cc/ci/nssm-2.24-101-g897c7ad.zip

From the NSSM website : "Windows 10 Creators Update

2017-04-26: Users of Windows 10 Creators Update should use prelease build 2.2.4-101 to avoid an issue with services failing to start. If for some reason you cannot use that build you can also set AppNoConsole=1 in the registry, noting that applications which expect a console window may behave unexpectedly.

Thanks to Sebasian Krause for the initial diagnosis."

Source : http://nssm.cc/download

**Comment by twangboy** [comment]
This is how it was fix on the Nullsoft side. We would like to stay away from unofficial builds when we can.
https://github.com/saltstack/salt/pull/40686

**Comment by markuskramerIgitt** [comment]
I took that over to the msi side 1st August 2018
https://github.com/markuskramerIgitt/salt-windows-msi/commit/ef2be1880a796187ae0d8846e207f20ba682e495

@yannj-fr, have you retried the msi installer since?

**Comment by markuskramerIgitt** [comment]
@twangboy or @xeacott, could you please close this issue?
