### ISSUE TITLE
Minion-specific msi-properties do not have any effect

### ISSUE THREAD

**Issue by Eagleman7** [saltstack/salt-windows-msi#19]
When Installing the MSI file with an elevated powershell prompt and executing the following command:

`PS C:\git\salt-windows-msi\wix.d\MinionMSI\bin\Release> msiexec /qb /i Salt-Minion-2017.7.0-24-ga71938c-64bit.msi START_MINION_SERVICE="1" MINION_HOSTNAME="minion123"`

It does not have any effect on the config file or the settings, the hostname stays the same and the service is not started.

The same with: `msiexec /x Salt-Minion-2016.11.6-64bit.msi KEEP_CONFIG="0"` It does not remove the config files.

How am I supposed to get the minion-specific msi-properties working? Am I doing something wrong or is the entire function broken?

**Comment by markuskramerIgitt** [comment]
@Eagleman7 sorry, I did not noticed your issue. I get no notification.
Probabybly not even on https://github.com/markuskramerIgitt/salt-windows-msi/issues

Please contact me the next time by citing me (@markuskramerIgitt). 

I am just closing my day, but I guess the quotes (") are not allowed.

KEEP_CONFIG="0" should be KEEP_CONFIG=0

Will look into that shortly.

**Comment by markuskramerIgitt** [comment]
@Eagleman7 Thank you for reporting this.

> MINION_HOSTNAME="minion123"

You correctly set the property on the command line, the program was wrongly overwriting the user input.

I fixed the bug in the above commit.

**Comment by markuskramerIgitt** [comment]
MINION_HOSTNAME renamed to MINION_ID

**Comment by markuskramerIgitt** [comment]
START_MINION_SERVICE renamed to START_MINION=""

START_MINION="" tested

**Comment by xeacott** [comment]
Is this an issue that we can close? @Eagleman7 Sorry just getting into this

**Comment by markuskramerIgitt** [comment]
@xeacott Could you please close this issue?

**Comment by xeacott** [comment]
Closed.
