### ISSUE TITLE
Build of 2015.2 is not working, No module named BaseHTTPServer

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt-windows-msi#2]
I don't know if these issues are watched since this is a bit outside the normal salt world but I'll try. 
First of, hats of to the work with these installers! It's really appreciated!

I've tried to setup our ci server to build salt minions using these and I've succedded in building a 2015.2-rc1 nsis installer. You can download the file [Salt-Minion-2015.2.0rc1-111-g0e8a47f-amd64-Setup.exe](https://readsoftdeploy.blob.core.windows.net/private-archive/salt-minion/Salt-Minion-2015.2.0rc1-111-g0e8a47f-amd64-Setup-2015.2.0rc1-111-g0e8a47f.exe?sv=2014-02-14&sr=b&sig=DNc5oInaMcZKKIsRhu%2Bf%2FMKi2pj%2BgXVsFhimXShdNxw%3D&se=2015-09-02T06%3A43%3A52Z&sp=r). 

Unfortunately I must be missing something since I cannot start this minion, I just get the following error:

```
2015-03-06 09:38:41,802 [salt.scripts     ][INFO    ][3016] Sleeping random_reauth_delay of 28 seconds
2015-03-06 09:39:10,262 [salt.cli.daemons ][INFO    ][2792] Setting up the Salt Minion "dev-eu-stbu-00"
2015-03-06 09:39:10,434 [salt.cli.daemons ][INFO    ][2792] The salt minion is shut down
2015-03-06 09:39:10,434 [salt.scripts     ][ERROR   ][2792] No module named BaseHTTPServer
2015-03-06 09:39:10,434 [salt.scripts     ][WARNING ][2792] ** Restarting minion **
```

From what I can see the BaseHTTPServer hase moved between python 2 and 3. But I think it's something else I've done wrong when producing my package. 

The full build log is [here](https://readsoftdeploy.blob.core.windows.net/archive/salt-minion-build.log). 

I get no errors but I' insure of how to pursue this, it seems like wrong packages are being added.

**Comment by andrejohansson** [comment]
ping @UtahDave and @saxonww

**Comment by saxonww** [comment]
I think this is a base salt issue, but I am not sure. The NSIS project in this repo is a modified copy of the one in the base salt repo here: https://github.com/saltstack/salt/tree/develop/pkg/windows/installer. There has been at least one code change there which I don't think was merged over here. I would try building from the base repo and see if it works; if it does, that would be helpful to know.

**Comment by andrejohansson** [comment]
I tried to fork and merge in the change you  mention, but that change only updatest the included vcredist package and doesn't seemt to have anything to do with BaseHTTPServer.

Should 2015.2rc1 be built with python3 instead of python2 perhaps?

**Comment by sosella** [comment]
I am seeing this same issue.  Has anyone come up with a fix for this?

**Comment by markuskramerIgitt** [comment]
@sosella: Yes, the msi is fixed 
@andrejohansson, In my world there are only Windows minions!

Please use the current version.


In 3 July, @saxonww has adapted the msi to Salt structural changes in commit
https://github.com/saxonww/salt-windows-msi/commit/68768b2a70dfe24d229e08aa6cf0e45c0b1e9bbc

In 13 Nov, his commit was merged as https://github.com/saltstack/salt-windows-msi/pull/9 in saltstack/salt-windows-msi

I continue @saxonww's development in https://github.com/markuskramerIgitt/salt-windows-msi
