### ISSUE TITLE
python27.dll missing

### ISSUE THREAD

**Issue by Eagleman7** [saltstack/salt-windows-msi#20]
When building the MSI with the following commands:

```
cd c:\git\salt
git clone -b 2017.7 https://github.com/saltstack/salt.git
cd c:\git\salt\pkg\windows
build.bat
cd c:\git\salt-windows-msi
yclean.cmd
ybuild.cmd
```

The service fails to start after installing the msi file. This is becuase python27.dll in C:\salt\bin is missing.

How can I make sure the python27.dll is installed when installing the msi file?

**Comment by tsaridas** [comment]
Hi,

I had to copy it manually when building the nsis exe in side c:\Python2.7\bin

**Comment by Eagleman7** [comment]
The issue was because I was building from the 2017.7 repo, I was not using the release version, which does indeed contain the python27.dll
