### ISSUE TITLE
Prebuilt MSI Files

### ISSUE THREAD

**Issue by Thoro** [saltstack/salt-windows-msi#44]
Are there anywhere msi files prebuilt available?

In specifically I'm looking for 2017.7.8

**Comment by markuskramerIgitt** [comment]
@Thoro , I am the current maintainer and only read your question now. 
Are you still interested in a prebuild Salt 2017.7.8  msi?  64-bit?

**Comment by Thoro** [comment]
Not anymore after the big security issue was discovered, is there one available somewhere for the newest version?

**Comment by markuskramerIgitt** [comment]
@Thoro minions cannot be attacked (directly) by the 2 latest CVEs 

I uploaded to my private Google drive these Python3 Minion msi's:
-   2019.2.3 https://drive.google.com/open?id=11SvHqxwXDP8tUc1lLl5TeMh8uRsKBGuk  
-   3000.2   https://drive.google.com/open?id=1Jvdgn3x9QSkOJOwJVy7oKSFwed5rgVdk
-   3000.3   https://drive.google.com/open?id=1iG_rbWa02KtU3Ci3cl6HtfcSuNba3qfv

I would kindly ask for your feedback.

## Build procedure

@twangboy I had to rename the v3000.3 exe. Is that a known issue or did I something wrong?
```
salt> git checkout v3000.3

salt\pks\windows> clean_env
salt\pks\windows> build Python=3
salt\pks\windows> cd installer
salt\pkg\windows\installer>move Salt-Minion-Python-Py3-AMD64-Setup.exe Salt-Minion-3000.3-Py3-AMD64-Setup.exe
salt-windows-msi> build


```

**Comment by Thoro** [comment]
I downloaded all 3 packages, I will try them out, but can't promise a quick response!

Is there a reason you don't just provide a Release build like other projects? Would be cool if the msi were just available under there.

**Comment by twangboy** [comment]
Salt will begin providing official MSI's in the upcoming Sodium release.

**Comment by markuskramerIgitt** [comment]
@Thoro  I uploaded the Python2 Minion you asked for
- 2017.7.8 https://drive.google.com/open?id=1jFK9Uxw_yDI5nwitQYu7VmdFcBVVy9gv
