### ISSUE TITLE
install switch and build question

### ISSUE THREAD

**Issue by jeffclay** [saltstack/salt-windows-msi#5]
Can you add the install switch to set a startup state? This really helps when upgrading minions. 

Also, when will we start seeing the MSI builds in http://docs.saltstack.com/downloads/  or are there not plans to release it in there with the regular build releases?

**Comment by jfindlay** [comment]
@jeffclay, that sounds like a great idea, thanks.  We're planning on creating MSI packages (to replace the NSI packages, I believe) but haven't finished the transition yet.

**Comment by saxonww** [comment]
@jeffclay, there is already a switch to control whether the minion service starts on install or not. It's available on one of the UI dialog screens during the setup, or you can pass START_MINION_SERVICE={0,1} on the msiexec command line. Is this what you're asking about?

**Comment by markuskramerIgitt** [comment]
@jeffclay and @jfindlay: we are several step towards releasing msi builds.
The msi works and need to get get built automatically (Jenkins).

Who can tell me how how to integrate msi build in Jenkins?

**Comment by markuskramerIgitt** [comment]
@jeffclay could you please describe what you mean with "startup state"?
- The state of the `salt-minion` Windows service?
- A Salt sls state executed by the minion on start?

**Comment by markuskramerIgitt** [comment]
@jeffclay, the msi are officially reased and support the `START_MINION` option.
