### ISSUE TITLE
Include *.msu packages in the assembly

### ISSUE THREAD

**Issue by berkut-174** [saltstack/salt-windows-msi#54]
Hi, I have a question about installing packages *.msu that come in a package *.exe for SaltStack. These updates (KB) are required for the application to work correctly. They are not included in the *.msi package.
I found that the WiX supports the ability to inlcude *.msu in the assembly https://wixtoolset.org/documentation/manual/v3/xsd/wix/msupackage.html.
But I can not do this, because I do not have enough knowledge for this.
Does anyone have an idea how to do this?

**Comment by berkut-174** [comment]
It looks like in this case there will already be an EXE package, not MSI https://wixtoolset.org/documentation/manual/v3/bundle/
Is it so ?

**Comment by markuskramerIgitt** [comment]
@berkut-174 Yes, you need a bundle to install an msu. 

msi are not intended to install msu.
