### ISSUE TITLE
Optionally flag the installation as a SystemComponent

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt-windows-msi#7]
It would be good if the Minion installers had a switch or MSI property to set the SystemComponent flag in their uninstall Registry key. This stops the installation being listed in Programs and Features.

Unfortunately I've had some installations removed because someone has seen it listed, decided that "Salt Minion" must be malware (because they didn't know what it was), and promptly uninstalled it. :-(

**Comment by markuskramerIgitt** [comment]
@morganwillcock, I think this is a good idea.

I never heard of SystemComponent before.
I have noticed that admins have stoped the service, and I think that Enlightenment needs time.


I am working on the "programmers issues" https://github.com/markuskramerIgitt/salt-windows-msi/issues

The issues here (https://github.com/saltstack/salt-windows-msi/issues) would then be "users issues".

**Comment by markuskramerIgitt** [comment]
Option is ARPSYSTEMCOMPONENT

Tested with 

    msiexec /i wix.d\MinionMSI\bin\Release\Salt-Minion-3001-Py3-AMD64.msi ARPSYSTEMCOMPONENT=1 /qb!

https://www.firegiant.com/wix/tutorial/com-expression-syntax-miscellanea/add-or-remove-programs-entries/

**Comment by markuskramerIgitt** [comment]
@morganwillcock thank you for the proposal: I just opened the above pull request for it.
